import type { ElectionStep } from '../types';

/**
 * The 8 phases of the Indian General Election process.
 * Each phase includes metadata for timeline display, detail panels, and chat integration.
 */
export const ELECTION_STEPS: ElectionStep[] = [
  {
    id: 1,
    phase: 'Phase 1',
    title: 'Election Announcement',
    description: 'The Election Commission of India (ECI) announces the election schedule, dates for each state, and the Model Code of Conduct kicks in.',
    detailedExplanation: 'The Election Commission of India (ECI) announces the election schedule through a formal press conference. This announcement includes polling dates for each state/constituency, the last date for filing nominations, and the date of counting. Once announced, the Model Code of Conduct comes into immediate effect. The ECI is an autonomous constitutional body responsible for administering elections in India. The announcement typically comes 6-8 weeks before the first phase of polling. The ECI also deploys election observers and sets up control rooms to monitor the process.',
    icon: 'megaphone',
    color: '#E65100',
    chatPrompt: 'Tell me about how elections are announced in India and what happens after the announcement.',
    typicalMonth: 'Feb–Mar',
    status: 'completed',
  },
  {
    id: 2,
    phase: 'Phase 2',
    title: 'Model Code of Conduct',
    description: 'Political parties and candidates must follow strict rules on campaigning, spending, and use of government resources.',
    detailedExplanation: 'The Model Code of Conduct (MCC) is a set of guidelines issued by the ECI for political parties and candidates to follow during elections. It comes into effect immediately after the election is announced. Key rules include: no new government schemes or projects can be announced, ministers cannot combine official visits with campaign work, no party can use government resources for campaigning, no appeal to caste or communal feelings, and campaign spending limits per constituency. The MCC ensures a level playing field and free & fair elections. Violations can lead to FIR filings and disqualification.',
    icon: 'shield',
    color: '#1A73E8',
    chatPrompt: 'What is the Model Code of Conduct and what rules must parties follow?',
    typicalMonth: 'Feb–Mar',
    status: 'completed',
  },
  {
    id: 3,
    phase: 'Phase 3',
    title: 'Voter Registration',
    description: 'Citizens can register, update, or verify their voter ID details at the nearest registration center or online via NVSP.',
    detailedExplanation: 'Voter registration is the process by which eligible citizens enroll to vote. In India, any citizen aged 18 or above on January 1 of the year can register. You can register online through the National Voters\' Service Portal (NVSP) at voters.eci.gov.in or by visiting your nearest voter registration center (usually your tehsil or BLO office). Required documents include age proof (birth certificate, school leaving certificate, or passport) and address proof (Aadhaar, utility bill, or ration card). After registration, you receive an EPIC (Electors Photo Identity Card) — your voter ID card. You can also update your address or correct details through Form 8A.',
    icon: 'clipboard',
    color: '#7B1FA2',
    chatPrompt: 'How do I register to vote in India? What documents do I need?',
    typicalMonth: 'Ongoing',
    status: 'completed',
  },
  {
    id: 4,
    phase: 'Phase 4',
    title: 'Nomination Filing',
    description: 'Candidates submit their nomination papers along with security deposit and affidavits of criminal and financial records.',
    detailedExplanation: 'Candidates who wish to contest elections must file their nomination papers with the Returning Officer of their constituency. The nomination form must include the candidate\'s personal details, party affiliation (or independent status), and an affidavit declaring criminal cases, assets, liabilities, and educational qualifications. A security deposit of ₹25,000 for general constituencies and ₹12,500 for SC/ST reserved constituencies must be paid. Nominations are scrutinized for validity, and candidates may withdraw within the specified period. The final list of contesting candidates is published after the withdrawal deadline.',
    icon: 'file-text',
    color: '#00897B',
    chatPrompt: 'How do candidates file their nominations? What documents are required?',
    typicalMonth: 'Mar',
    status: 'current',
  },
  {
    id: 5,
    phase: 'Phase 5',
    title: 'Campaign Period',
    description: 'Candidates and parties hold rallies, roadshows, and media campaigns to persuade voters. Campaigning must stop 48 hours before polling.',
    detailedExplanation: 'The campaign period is when candidates and political parties reach out to voters through rallies, door-to-door canvassing, media advertisements, social media campaigns, and roadshows. The ECI regulates campaign spending — currently ₹95 lakh per Lok Sabha constituency and ₹40 lakh per Assembly constituency. Campaigns must stop 48 hours before polling day ("silent period") to give voters time to make their decision without influence. Paid news, hate speech, and use of religious venues for campaigning are prohibited. The ECI monitors campaign spending through expenditure observers and can take action against violations.',
    icon: 'users',
    color: '#F9A825',
    chatPrompt: 'Tell me about election campaigns in India. What are the rules and spending limits?',
    typicalMonth: 'Mar–Apr',
    status: 'upcoming',
  },
  {
    id: 6,
    phase: 'Phase 6',
    title: 'Polling Day',
    description: 'Voters visit their assigned polling booth, verify identity, and cast their vote using an Electronic Voting Machine (EVM).',
    detailedExplanation: 'On polling day, voters go to their assigned polling booth (found on the voter slip or NVSP portal). At the booth: 1) Queue up — separate lines for men, women, and seniors. 2) Show your voter ID (EPIC) or any of 12 approved photo IDs (Aadhaar, passport, driving license, etc.). 3) The polling officer checks your name in the electoral roll and applies indelible ink to your left index finger. 4) Enter the voting compartment. 5) Press the button next to your chosen candidate on the EVM. 6) The VVPAT machine prints a slip showing your vote for 7 seconds — verify it. 7) Exit the booth. Polling hours are typically 7 AM to 6 PM. It is a paid holiday for all employees.',
    icon: 'vote',
    color: '#2E7D32',
    chatPrompt: 'How does voting work on polling day? What should I carry to the polling booth?',
    typicalMonth: 'Apr–May',
    status: 'upcoming',
  },
  {
    id: 7,
    phase: 'Phase 7',
    title: 'Vote Counting',
    description: 'EVMs are transported to counting centers under tight security. Votes are tallied round by round in the presence of candidates\' agents.',
    detailedExplanation: 'After polling ends, the EVMs are sealed and transported under armed security to designated counting centers (usually in district headquarters). On counting day, the EVMs are opened in the presence of the Returning Officer, counting agents of candidates, and ECI observers. Counting happens round by round — each round involves opening a set of EVMs. Postal ballots (used by service voters and those on election duty) are counted first. The VVPAT slips of 5 randomly selected booths per constituency are matched with EVM results as a verification measure. Results are displayed on a counting board after each round. The entire process is supervised by the ECI to ensure transparency.',
    icon: 'bar-chart',
    color: '#C62828',
    chatPrompt: 'How are votes counted? How do EVMs and VVPAT verification work?',
    typicalMonth: 'May–Jun',
    status: 'upcoming',
  },
  {
    id: 8,
    phase: 'Phase 8',
    title: 'Result Declaration',
    description: 'The candidate with the most votes wins. Results are declared constituency by constituency and the party with majority forms the government.',
    detailedExplanation: 'After all rounds of counting are complete, the Returning Officer declares the winning candidate — the one with the most votes (First Past The Post system). Results are announced constituency by constituency, and the ECI publishes them in real-time on results.eci.gov.in. For the Lok Sabha, a party or alliance needs 272 out of 543 seats to form the government. The President invites the leader of the majority party/alliance to form the government. If no party gets a clear majority, post-election alliances are formed. The entire process from announcement to results typically takes 2-3 months. The swearing-in of the new government usually happens within days of the final results.',
    icon: 'trophy',
    color: '#FF8F00',
    chatPrompt: 'How are election results declared? How is the winner decided?',
    typicalMonth: 'Jun',
    status: 'upcoming',
  },
];
